# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syssyaaccount',
            options={},
        ),
    ]
