# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_tables', '0003_auto_20151210_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysrlnsyasym',
            options={'managed': False},
        ),
    ]
